//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFFiveSessionWindowsFormApp.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.FaultTypes = new HashSet<FaultTypes>();
        }
    
        public int ProductId { get; set; }
        public int ProductTypeId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> RepairStatusId { get; set; }
        public string Name { get; set; }
        public string ProductNumber { get; set; }
        public string DeliveryCustomer { get; set; }
        public bool IsBoxed { get; set; }
        public System.DateTime TakeDate { get; set; }
        public string Description { get; set; }
    
        public virtual ProductTypes ProductTypes { get; set; }
        public virtual RepairSituations RepairSituations { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FaultTypes> FaultTypes { get; set; }
    }
}
