//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFFiveSessionWindowsFormApp.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetails
    {
        public int UserId { get; set; }
        public System.DateTime Birthdate { get; set; }
        public string Address { get; set; }
        public bool Gender { get; set; }
        public string PhoneNumber { get; set; }
        public System.DateTime RegisterDate { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
